export const COLOR_WHITE = '#FFFFFF'
export const COLOR_DARK_WHITE = '#E5E5E7'
export const COLOR_BLACK = '#000'

export const COLOR_LIGHT_RED = '#E76B5C'
export const COLOR_LIGHT_BLUE = '#4E4981'
export const COLOR_LIGHT_PRIMARY = '#86878C'
export const COLOR_LIGHT_SECONDARY = '#BDBFC4'
export const COLOR_LIGHT_THIRD = '#D3D5DA'
// export const COLOR_LIGHT_FOURTH = '#'
export const COLOR_LIGHT_BG = '#F2F2F2'

export const COLOR_DARK_RED = '#E16A5B'
export const COLOR_DARK_BLUE = '#635CB4'
export const COLOR_DARK_PRIMARY = '#9B9AA3'
export const COLOR_DARK_SECONDARY = '#5E5D64'
export const COLOR_DARK_THIRD = '#46454C'
export const COLOR_DARK_FOURTH = '#272728'
export const COLOR_DARK_BG = '#222127'